# Prometheus Configuration for Aegis Platform
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'aegis-platform'

rule_files:
  - "/etc/prometheus/alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Aegis Backend API
  - job_name: 'aegis-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: '/nginx_status'
    scrape_interval: 15s

  # MySQL database
  - job_name: 'mysql'
    static_configs:
      - targets: ['db:3306']
    scrape_interval: 15s

  # Redis cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Application-specific metrics
  - job_name: 'aegis-app-metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/v1/metrics/application'
    scrape_interval: 30s
    basic_auth:
      username: 'prometheus'
      password: 'secure_prometheus_password'