# ==============================================
# Aegis Platform - Prometheus Configuration
# ==============================================
# This configuration sets up comprehensive monitoring for:
# - Application metrics and performance
# - Infrastructure monitoring
# - Security metrics and alerts
# - Business metrics
# ==============================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'aegis-production'
    environment: 'production'

# Rule files for alerting
rule_files:
  - "alert_rules/*.yml"
  - "recording_rules/*.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # Aegis Backend Application
  - job_name: 'aegis-backend'
    static_configs:
      - targets: ['aegis-backend:8000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Aegis Frontend (nginx metrics)
  - job_name: 'aegis-frontend-nginx'
    static_configs:
      - targets: ['aegis-frontend:80']
    metrics_path: /nginx_status
    scrape_interval: 15s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node Exporter (System metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor (Container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # Nginx Prometheus Exporter
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

  # Blackbox Exporter (External monitoring)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://yourdomain.com
        - https://yourdomain.com/health
        - https://yourdomain.com/api/v1/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # SSL Certificate Monitoring
  - job_name: 'ssl-cert-check'
    metrics_path: /probe
    params:
      module: [ssl_cert_check]
    static_configs:
      - targets:
        - yourdomain.com:443
        - www.yourdomain.com:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom application metrics
  - job_name: 'aegis-custom-metrics'
    static_configs:
      - targets: ['aegis-backend:8000']
    metrics_path: /api/v1/metrics/custom
    scrape_interval: 30s
    honor_labels: true

# Remote write configuration (for external monitoring services)
# Uncomment and configure as needed
# remote_write:
#   - url: "https://prometheus-us-central1.grafana.net/api/prom/push"
#     basic_auth:
#       username: "your-grafana-cloud-username"
#       password: "your-grafana-cloud-password"

# Storage configuration
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 30d
    retention.size: 50GB
    wal-compression: true

# Performance tuning
query:
  max_concurrency: 20
  max_samples: 50000000
  timeout: 2m

# Security configuration
web:
  enable_lifecycle: true
  enable_admin_api: false
  max_connections: 512
  read_timeout: 30s
  external_url: "https://prometheus.yourdomain.com"