# Aegis Platform - Prometheus Configuration (Bundled Production)
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Aegis Backend Health Check
  - job_name: 'aegis-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/health'
    scrape_interval: 30s

  # Aegis Frontend Health Check  
  - job_name: 'aegis-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/'
    scrape_interval: 30s